import IncidenceCubes
#print axioms IncidenceCubes.Penrose.bottom_edge
#print axioms IncidenceCubes.Penrose.middle_edge
#print axioms IncidenceCubes.Penrose.top_edge
#print axioms IncidenceCubes.Penrose.exists_algebraic_eighth
#print axioms IncidenceCubes.Penrose.face_pencil_identity
#print axioms IncidenceCubes.Penrose.top_face_common_zero
#print axioms IncidenceCubes.Penrose.polar_rank_one_update
#print axioms IncidenceCubes.Penrose.polar_agrees_on_chord
#print axioms IncidenceCubes.Fomin.total_product
#print axioms IncidenceCubes.Fomin.last_face
#print axioms IncidenceCubes.Fomin.cube_last_face
#print axioms IncidenceCubes.Fomin.cross_dot_identity
#print axioms IncidenceCubes.Fomin.ratio_one_iff_incident
#print axioms IncidenceCubes.Connection.eval_doubleLine
#print axioms IncidenceCubes.Connection.doubleLine_rescale
#print axioms IncidenceCubes.Connection.doubleLine_ne_zero
#print axioms IncidenceCubes.Connection.rank_one_pencil

-- Classical baseline and local determinantal comparison.
#print axioms IncidenceCubes.Classical.pair_comm
#print axioms IncidenceCubes.Classical.cross_left_incident
#print axioms IncidenceCubes.Classical.cross_right_incident
#print axioms IncidenceCubes.Classical.bracket_cyclic
#print axioms IncidenceCubes.Classical.bracket_swap
#print axioms IncidenceCubes.Classical.bracket_scale
#print axioms IncidenceCubes.Classical.cross_scale
#print axioms IncidenceCubes.Classical.bracket_eq_det
#print axioms IncidenceCubes.Classical.det_zero_iff_kernel
#print axioms IncidenceCubes.Classical.collinear_iff_bracket
#print axioms IncidenceCubes.Classical.concurrent_iff_collinear
#print axioms IncidenceCubes.Classical.concurrent_iff_bracket
#print axioms IncidenceCubes.Classical.collinear_rescale
#print axioms IncidenceCubes.Classical.concurrent_rescale
#print axioms IncidenceCubes.Classical.conicEval_matrixCoefficients
#print axioms IncidenceCubes.Classical.polars_on_common_conic
#print axioms IncidenceCubes.Classical.brianchon
#print axioms IncidenceCubes.Classical.onCommonConic_iff_det
#print axioms IncidenceCubes.Classical.pascal
#print axioms IncidenceCubes.Classical.braikenridge_maclaurin_iff
#print axioms IncidenceCubes.Classical.brianchon_dual_conic
#print axioms IncidenceCubes.Classical.PascalInput.conclusion
#print axioms IncidenceCubes.Classical.pappus_identity
#print axioms IncidenceCubes.Classical.desargues_identity
#print axioms IncidenceCubes.Classical.pappus
#print axioms IncidenceCubes.Classical.dual_pappus
#print axioms IncidenceCubes.Classical.desargues
#print axioms IncidenceCubes.Classical.desargues_iff
#print axioms IncidenceCubes.Classical.dual_desargues
#print axioms IncidenceCubes.Classical.PappusInput.conclusion
#print axioms IncidenceCubes.Classical.pascal_identity
#print axioms IncidenceCubes.Classical.inverse_polar
#print axioms IncidenceCubes.Classical.polar_ne_zero
#print axioms IncidenceCubes.Classical.polar_on_dual_quadric
#print axioms IncidenceCubes.Classical.inverse_symmetric
#print axioms IncidenceCubes.Classical.matrixCoefficients_ne_zero
#print axioms IncidenceCubes.Classical.inverse_det_ne_zero
#print axioms IncidenceCubes.Classical.polar_tangent_expansion
#print axioms IncidenceCubes.Classical.DesarguesInput.conclusion
#print axioms IncidenceCubes.Classical.BrianchonInput.conclusion
#print axioms IncidenceCubes.Classical.menelaus_identity
#print axioms IncidenceCubes.Classical.ceva_identity
#print axioms IncidenceCubes.Classical.menelaus_iff
#print axioms IncidenceCubes.Classical.ceva_iff
#print axioms IncidenceCubes.Connection.Determinantal.exchange
#print axioms IncidenceCubes.Connection.Determinantal.bordered_eq_det
#print axioms IncidenceCubes.Connection.Determinantal.symmetric_exchange
#print axioms IncidenceCubes.Connection.Determinantal.eliminate_two
#print axioms IncidenceCubes.Connection.Determinantal.elimination_commutes
#print axioms IncidenceCubes.Connection.Determinantal.pivot_commutes
#print axioms IncidenceCubes.Connection.Determinantal.pivot_preserves_symmetry
#print axioms IncidenceCubes.Connection.Determinantal.fomin_face_iff_zero_pivot
#print axioms IncidenceCubes.Connection.Determinantal.defect_ratio
#print axioms IncidenceCubes.Connection.Determinantal.torus_commutator_counterexample
#print axioms IncidenceCubes.Connection.penrose_middle_via_symmetric_exchange
#print axioms IncidenceCubes.Connection.fomin_coherence_via_zero_pivot
#print axioms IncidenceCubes.Connection.fomin_coherence_iff_classical_collinear
