import IncidenceCubes
#print axioms IncidenceCubes.Penrose.bottom_edge
#print axioms IncidenceCubes.Penrose.middle_edge
#print axioms IncidenceCubes.Penrose.top_edge
#print axioms IncidenceCubes.Penrose.exists_algebraic_eighth
#print axioms IncidenceCubes.Penrose.face_pencil_identity
#print axioms IncidenceCubes.Penrose.top_face_common_zero
#print axioms IncidenceCubes.Penrose.polar_rank_one_update
#print axioms IncidenceCubes.Penrose.polar_agrees_on_chord
#print axioms IncidenceCubes.Fomin.total_product
#print axioms IncidenceCubes.Fomin.last_face
#print axioms IncidenceCubes.Fomin.cube_last_face
#print axioms IncidenceCubes.Fomin.cross_dot_identity
#print axioms IncidenceCubes.Fomin.ratio_one_iff_incident
#print axioms IncidenceCubes.Connection.eval_doubleLine
#print axioms IncidenceCubes.Connection.doubleLine_rescale
#print axioms IncidenceCubes.Connection.doubleLine_ne_zero
#print axioms IncidenceCubes.Connection.rank_one_pencil

-- Classical baseline and local determinantal comparison.
#print axioms IncidenceCubes.Classical.pair_comm
#print axioms IncidenceCubes.Classical.cross_left_incident
#print axioms IncidenceCubes.Classical.cross_right_incident
#print axioms IncidenceCubes.Classical.bracket_cyclic
#print axioms IncidenceCubes.Classical.bracket_swap
#print axioms IncidenceCubes.Classical.bracket_scale
#print axioms IncidenceCubes.Classical.cross_scale
#print axioms IncidenceCubes.Classical.bracket_eq_det
#print axioms IncidenceCubes.Classical.det_zero_iff_kernel
#print axioms IncidenceCubes.Classical.collinear_iff_bracket
#print axioms IncidenceCubes.Classical.concurrent_iff_collinear
#print axioms IncidenceCubes.Classical.concurrent_iff_bracket
#print axioms IncidenceCubes.Classical.collinear_rescale
#print axioms IncidenceCubes.Classical.concurrent_rescale
#print axioms IncidenceCubes.Classical.conicEval_matrixCoefficients
#print axioms IncidenceCubes.Classical.polars_on_common_conic
#print axioms IncidenceCubes.Classical.brianchon
#print axioms IncidenceCubes.Classical.onCommonConic_iff_det
#print axioms IncidenceCubes.Classical.pascal
#print axioms IncidenceCubes.Classical.braikenridge_maclaurin_iff
#print axioms IncidenceCubes.Classical.brianchon_dual_conic
#print axioms IncidenceCubes.Classical.PascalInput.conclusion
#print axioms IncidenceCubes.Classical.pappus_identity
#print axioms IncidenceCubes.Classical.desargues_identity
#print axioms IncidenceCubes.Classical.pappus
#print axioms IncidenceCubes.Classical.dual_pappus
#print axioms IncidenceCubes.Classical.desargues
#print axioms IncidenceCubes.Classical.desargues_iff
#print axioms IncidenceCubes.Classical.dual_desargues
#print axioms IncidenceCubes.Classical.PappusInput.conclusion
#print axioms IncidenceCubes.Classical.pascal_identity
#print axioms IncidenceCubes.Classical.inverse_polar
#print axioms IncidenceCubes.Classical.polar_ne_zero
#print axioms IncidenceCubes.Classical.polar_on_dual_quadric
#print axioms IncidenceCubes.Classical.inverse_symmetric
#print axioms IncidenceCubes.Classical.matrixCoefficients_ne_zero
#print axioms IncidenceCubes.Classical.inverse_det_ne_zero
#print axioms IncidenceCubes.Classical.polar_tangent_expansion
#print axioms IncidenceCubes.Classical.DesarguesInput.conclusion
#print axioms IncidenceCubes.Classical.BrianchonInput.conclusion
#print axioms IncidenceCubes.Classical.menelaus_identity
#print axioms IncidenceCubes.Classical.ceva_identity
#print axioms IncidenceCubes.Classical.menelaus_iff
#print axioms IncidenceCubes.Classical.ceva_iff
#print axioms IncidenceCubes.Connection.Determinantal.exchange
#print axioms IncidenceCubes.Connection.Determinantal.bordered_eq_det
#print axioms IncidenceCubes.Connection.Determinantal.symmetric_exchange
#print axioms IncidenceCubes.Connection.Determinantal.eliminate_two
#print axioms IncidenceCubes.Connection.Determinantal.elimination_commutes
#print axioms IncidenceCubes.Connection.Determinantal.pivot_commutes
#print axioms IncidenceCubes.Connection.Determinantal.pivot_preserves_symmetry
#print axioms IncidenceCubes.Connection.Determinantal.fomin_face_iff_zero_pivot
#print axioms IncidenceCubes.Connection.Determinantal.defect_ratio
#print axioms IncidenceCubes.Connection.Determinantal.torus_commutator_counterexample
#print axioms IncidenceCubes.Connection.penrose_middle_via_symmetric_exchange
#print axioms IncidenceCubes.Connection.fomin_coherence_via_zero_pivot
#print axioms IncidenceCubes.Connection.fomin_coherence_iff_classical_collinear

-- Staged determinant expansion and defect-surface calculus.
#print axioms IncidenceCubes.Classical.det_four_scalar
#print axioms IncidenceCubes.Classical.det_five_scalar
#print axioms IncidenceCubes.Classical.det_six_scalar
#print axioms IncidenceCubes.Connection.DefectSurface.denominator_ne_zero
#print axioms IncidenceCubes.Connection.DefectSurface.face_ratio
#print axioms IncidenceCubes.Connection.DefectSurface.total_defect_product
#print axioms IncidenceCubes.Connection.DefectSurface.factorized_product
#print axioms IncidenceCubes.Connection.DefectSurface.symmetric_product
#print axioms IncidenceCubes.Connection.DefectSurface.coherent_iff_defect_zero
#print axioms IncidenceCubes.Connection.DefectSurface.last_defect_zero
#print axioms IncidenceCubes.Connection.DefectSurface.last_factor_vanishes
#print axioms IncidenceCubes.Connection.DefectSurface.last_square_root_zero
#print axioms IncidenceCubes.Connection.DefectSurface.positive_square_obstruction

-- Generic arbitrary-input Penrose completion, uniqueness and tangency.
#print axioms IncidenceCubes.Penrose.Completion.middle_identity
#print axioms IncidenceCubes.Penrose.Completion.double_swap
#print axioms IncidenceCubes.Penrose.Completion.triple_identity
#print axioms IncidenceCubes.Penrose.Completion.all_top_identities
#print axioms IncidenceCubes.Penrose.Completion.matrix_diagonal
#print axioms IncidenceCubes.Penrose.Completion.matrix_symmetric
#print axioms IncidenceCubes.Penrose.Completion.matrix_edge
#print axioms IncidenceCubes.Penrose.Completion.pairing_row
#print axioms IncidenceCubes.Penrose.Completion.pairing_middle
#print axioms IncidenceCubes.Penrose.Completion.pairing_last
#print axioms IncidenceCubes.Penrose.Completion.middleChord_ne
#print axioms IncidenceCubes.Penrose.Completion.topChord_ne
#print axioms IncidenceCubes.Penrose.Completion.top_contact
#print axioms IncidenceCubes.Penrose.Completion.contact_target_ne
#print axioms IncidenceCubes.Penrose.Completion.result_ne
#print axioms IncidenceCubes.Penrose.Completion.canonical_middle_contact
#print axioms IncidenceCubes.Penrose.Completion.canonical_upper_contact
#print axioms IncidenceCubes.Penrose.Completion.original_upper_contact
#print axioms IncidenceCubes.Penrose.Completion.original_upper_kernel
#print axioms IncidenceCubes.Penrose.Completion.facePoint_pair
#print axioms IncidenceCubes.Penrose.Completion.facePoint_ne
#print axioms IncidenceCubes.Penrose.Completion.facePoint_upper
#print axioms IncidenceCubes.Penrose.Completion.facePoint_top
#print axioms IncidenceCubes.Penrose.Completion.new_faces_concurrent
#print axioms IncidenceCubes.Penrose.Completion.result_symmetric
#print axioms IncidenceCubes.Penrose.Completion.seven_completion
#print axioms IncidenceCubes.Penrose.Geometry.value_square
#print axioms IncidenceCubes.Penrose.Geometry.value_combination
#print axioms IncidenceCubes.Penrose.Geometry.contact_polar
#print axioms IncidenceCubes.Penrose.Geometry.rank_two_determinant
#print axioms IncidenceCubes.Penrose.Geometry.contact_coefficient_unique
#print axioms IncidenceCubes.Penrose.Geometry.contact_chord_kernel
#print axioms IncidenceCubes.Penrose.Geometry.Contact.rescale_left
#print axioms IncidenceCubes.Penrose.Geometry.Contact.rescale_right
#print axioms IncidenceCubes.Penrose.Geometry.initial_normal_form
#print axioms IncidenceCubes.Penrose.Geometry.pull_square
#print axioms IncidenceCubes.Penrose.Geometry.pull_smul
#print axioms IncidenceCubes.Penrose.Geometry.pull_combination
#print axioms IncidenceCubes.Penrose.Geometry.pull_comp
#print axioms IncidenceCubes.Penrose.Geometry.pull_identity
#print axioms IncidenceCubes.Penrose.Geometry.pullLine_comp
#print axioms IncidenceCubes.Penrose.Geometry.pullLine_identity
#print axioms IncidenceCubes.Penrose.Geometry.pull_injective
#print axioms IncidenceCubes.Penrose.Geometry.pullLine_injective
#print axioms IncidenceCubes.Penrose.Geometry.Contact.pull
#print axioms IncidenceCubes.Penrose.Geometry.pairing_axis_left
#print axioms IncidenceCubes.Penrose.Geometry.pairing_axis_right
#print axioms IncidenceCubes.Penrose.Geometry.pairing_scale
#print axioms IncidenceCubes.Penrose.Geometry.value_axis
#print axioms IncidenceCubes.Penrose.Geometry.value_scale
#print axioms IncidenceCubes.Penrose.Geometry.face_axis_coordinates
#print axioms IncidenceCubes.Penrose.Geometry.pairing_pull
#print axioms IncidenceCubes.Penrose.Geometry.value_pull
#print axioms IncidenceCubes.Penrose.Geometry.FaceOff.pull
#print axioms IncidenceCubes.Penrose.Geometry.pull_row
#print axioms IncidenceCubes.Penrose.Geometry.pull_single
#print axioms IncidenceCubes.Penrose.Geometry.pull_double
#print axioms IncidenceCubes.Penrose.Geometry.proportional_of_pull
#print axioms IncidenceCubes.Penrose.Geometry.arbitrary_face_normal_form
#print axioms IncidenceCubes.Penrose.Examples.rational_independent_faces
#print axioms IncidenceCubes.Penrose.Examples.rational_completion
#print axioms IncidenceCubes.Penrose.Normalization.binary_normal_form
#print axioms IncidenceCubes.Penrose.Normalization.square_add
#print axioms IncidenceCubes.Penrose.Normalization.face_normal_form
#print axioms IncidenceCubes.Penrose.GeometricSeven.seven_normal_form
#print axioms IncidenceCubes.Penrose.Tangency.value_add_axes
#print axioms IncidenceCubes.Penrose.Tangency.nonzero_equation
#print axioms IncidenceCubes.Penrose.Tangency.polar_nonzero
#print axioms IncidenceCubes.Penrose.Tangency.tangent_expansion
#print axioms IncidenceCubes.Penrose.Tangency.columns_det
#print axioms IncidenceCubes.Penrose.Tangency.mulVec_axis
#print axioms IncidenceCubes.Penrose.Tangency.pull_symmetric
#print axioms IncidenceCubes.Penrose.Tangency.pull_regular
#print axioms IncidenceCubes.Penrose.Tangency.contact_of_two_tangencies
#print axioms IncidenceCubes.Penrose.Tangency.contact_iff_two_tangencies
#print axioms IncidenceCubes.Penrose.Tangency.generic_nonzero_equation
#print axioms IncidenceCubes.Penrose.Theorem.TwoPointContact.to_contact
#print axioms IncidenceCubes.Penrose.Theorem.penrose_from_tangencies
#print axioms IncidenceCubes.Penrose.Theorem.completion_tangent_at_section
#print axioms IncidenceCubes.Penrose.Uniqueness.forced_face_point
#print axioms IncidenceCubes.Penrose.Uniqueness.faceFrame_column
#print axioms IncidenceCubes.Penrose.Uniqueness.matrix_det
#print axioms IncidenceCubes.Penrose.Uniqueness.faceFrame_det
#print axioms IncidenceCubes.Penrose.Uniqueness.fullDet_of_independent_faces
#print axioms IncidenceCubes.Penrose.Uniqueness.completion_chord_at_face
#print axioms IncidenceCubes.Penrose.Uniqueness.top_at_other
#print axioms IncidenceCubes.Penrose.Uniqueness.line_through_frame_pair
#print axioms IncidenceCubes.Penrose.Uniqueness.completion_chord_proportional
#print axioms IncidenceCubes.Penrose.Uniqueness.square_scale
#print axioms IncidenceCubes.Penrose.Uniqueness.Contact.rescale_chord
#print axioms IncidenceCubes.Penrose.Uniqueness.value_smul
#print axioms IncidenceCubes.Penrose.Uniqueness.two_pencils_unique
#print axioms IncidenceCubes.Penrose.Uniqueness.completion_unique
#print axioms IncidenceCubes.Penrose.Uniqueness.penrose_generic

-- Fomin-to-conics contact transport and geometric surface theorems.
#print axioms IncidenceCubes.Connection.ConicTransport.Witness.contact
#print axioms IncidenceCubes.Connection.ConicTransport.scale_unique
#print axioms IncidenceCubes.Connection.ConicTransport.face_gauge_invariant
#print axioms IncidenceCubes.Connection.ConicTransport.det_three_squares
#print axioms IncidenceCubes.Connection.ConicTransport.det_single_square
#print axioms IncidenceCubes.Connection.ConicTransport.four_squares_concurrent
#print axioms IncidenceCubes.Connection.ConicTransport.face_balance
#print axioms IncidenceCubes.Connection.ConicTransport.square_mulVec
#print axioms IncidenceCubes.Connection.ConicTransport.concurrence_implies_balance
#print axioms IncidenceCubes.Connection.ConicTransport.face_concurrent_iff
#print axioms IncidenceCubes.Connection.GeometricSurface.ConicNet.coherent_iff_weight
#print axioms IncidenceCubes.Connection.GeometricSurface.conic_surface_last_face
#print axioms IncidenceCubes.Connection.GeometricSurface.conic_total_holonomy
#print axioms IncidenceCubes.Connection.GeometricSurface.PointLineNet.weight_val
#print axioms IncidenceCubes.Connection.GeometricSurface.PointLineNet.coherent_iff_weight
#print axioms IncidenceCubes.Connection.GeometricSurface.point_line_surface_last_face
#print axioms IncidenceCubes.Connection.SurfaceApplications.conic_surface_from_tangencies
#print axioms IncidenceCubes.Connection.SurfaceApplications.conic_cube_five_faces
#print axioms IncidenceCubes.Connection.SurfaceApplications.point_line_cube_five_faces
#print axioms IncidenceCubes.Connection.HyperplaneSurface.coherent_iff_minor
#print axioms IncidenceCubes.Connection.HyperplaneSurface.Net.weight_val
#print axioms IncidenceCubes.Connection.HyperplaneSurface.Net.coherent_iff_weight
#print axioms IncidenceCubes.Connection.HyperplaneSurface.hyperplane_surface_last_face
#print axioms IncidenceCubes.Connection.TransportExamples.all_regular
#print axioms IncidenceCubes.Connection.TransportExamples.all_symmetric
#print axioms IncidenceCubes.Connection.TransportExamples.all_contacts
#print axioms IncidenceCubes.Connection.TransportExamples.nontrivial_transport
#print axioms IncidenceCubes.Connection.TransportExamples.not_concurrent

-- Classical/Presentation
#print axioms IncidenceCubes.Presentation.linePair_eval
#print axioms IncidenceCubes.Presentation.linePair_ne_zero
#print axioms IncidenceCubes.Presentation.pappus_via_pascal
#print axioms IncidenceCubes.Presentation.contact_split_normalization
#print axioms IncidenceCubes.Presentation.salmon_concurrence
#print axioms IncidenceCubes.Presentation.salmon_factor
#print axioms IncidenceCubes.Presentation.salmon_common_section
#print axioms IncidenceCubes.Presentation.salmon_from_contacts

-- Classical/Spatial
#print axioms IncidenceCubes.Spatial.segre_on_quadric
#print axioms IncidenceCubes.Spatial.same_ruling_polar
#print axioms IncidenceCubes.Spatial.dandelin_tangent_plane
#print axioms IncidenceCubes.Spatial.trace_incidence
#print axioms IncidenceCubes.Spatial.plane_section_collinear
#print axioms IncidenceCubes.Spatial.lift_rank_one

-- Connection/TorusExample
#print axioms IncidenceCubes.Connection.TorusExample.fifteen_faces
#print axioms IncidenceCubes.Connection.TorusExample.sixteenth_face

-- Orientation-only surface and boundary extension.
#print axioms IncidenceCubes.Connection.OrientedSurface.total_holonomy
#print axioms IncidenceCubes.Connection.OrientedSurface.region_boundary
#print axioms IncidenceCubes.Connection.OrientedSurface.internal_edge_cancels
#print axioms IncidenceCubes.Connection.OrientedSurface.cyclic_face_concurrent_iff
#print axioms IncidenceCubes.Connection.OrientedSurface.ConicNet.side_relation
#print axioms IncidenceCubes.Connection.OrientedSurface.ConicNet.coherent_iff_holonomy
#print axioms IncidenceCubes.Connection.OrientedSurface.conic_surface_last_face
#print axioms IncidenceCubes.Connection.OrientedSurface.coherent_region_boundary
#print axioms IncidenceCubes.Connection.OrientedExample.not_bicolorable
#print axioms IncidenceCubes.Connection.OrientedExample.first_eleven
#print axioms IncidenceCubes.Connection.OrientedExample.twelfth_face
